### ISSUE TITLE
Add PassSec+ to addons.mozilla.org

### ISSUE THREAD

**Issue by c33s** [SecUSo/PassSec-plus#6]
mozilla is blocking addons, which are unsigned, since [firefox 43][1], there it is possible to override the behavior there via setting, and mozilla announced they will remove this option with [firefox 46][2], it would be great to see this addon on http://addons.mozilla.org

[1]: https://blog.mozilla.org/addons/2016/01/22/add-on-signing-update/
[2]: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by krisbr** [comment]
Thanks for the suggestion. Please download the newest version of the add-on (1.2.0) from our [website](https://www.secuso.org/passsec) or the GitHub release page, because this one should be signed. I hope that it solves your problem.

**Comment by c33s** [comment]
thank you very much. the "signing problem" is gone.

still it would be cool to add it to addons.mozilla.org.

**Comment by c33s** [comment]
so you wont add it to mozilla? :(

**Comment by krisbr** [comment]
Sorry, I've added a comment but it disappeared when I closed the bug. Unfortunately it's not possible to publish it on the Mozilla website, because we decided to sign it ourselves. Then it's not possible to publish it on the Mozilla website anymore. We decided to do it this way because we are can distribute updates much faster.

**Comment by rugk** [comment]
It has been added here FYI: https://addons.mozilla.org/de/firefox/addon/passsec/

**Comment by krisbr** [comment]
Thanks for mentioning it here, I forgot to update this thread.
