### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by beerisgood** [SecUSo/PassSec-plus#7]
First, thanks for this addon!

I would like it use with Pale Moon (http://www.palemoon.org) but i get this output in error console:
`Error: NS_ERROR_NOT_INITIALIZED: Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [mozIStorageConnection.lastErrorString]
Source File: chrome://firefoxpasswordwarningextension/content/lib/database.js
Line: 151`

Addon install fine and i get the info all works and addon installation was successful, but it doesn't work.

Adding recommend exception doesn't work too. It say "ok" but no entries are in the list.

Test with x86 and x64 Pale Moon with clean profile.

**Comment by krisbr** [comment]
Thanks for your report.
I was able to reproduce the bug with the current version of Pale Moon. Unfortunately I did not find out why it happens. The creation of the database works with no problems and then it should be initialized. 

I'll keep looking for it but since there is no problem with Firefox, which is our primary focus, and our development resources are limited I don't want to promise fixing it. I hope you can understand that.

**Comment by janekptacijarabaci** [comment]
See also https://forum.palemoon.org/viewtopic.php?f=46&t=11661#p82219

**Comment by beerisgood** [comment]
A small update:
Moonchild (the Pale Moon dev) wrote this:
> Shouldn't be too difficult to address this sqlite connection state issue. I'll see if I can slip this in for 26.2

If Pale Moon 26.2 fix this, i will post it here.

**Comment by wolfbeast** [comment]
Unfortunately the sqlite/storage connection logic flaw was apparently not the root cause for this extension compatibility issue. If more information is available from the extension side of things (exactly what is attempted, and what does it error on?) then that would probably help -- unfortunately there's a rather large glob of potential Mozilla bugs to look at.

**Comment by krisbr** [comment]
Thanks for your help, it's very kind that you want to fix it! Of course it would be really nice to support another browser.

The bug/problem seems to happen in the isInside function. The add-on tries to check whether the URL the user currently visits is in a specific database. Theoretically, when a user installs the add-on for the first time, the database should be created and obviously the specific URL isn't in that database/table.
I'll debug it and try to find out more about the bug. Unfortunately I don't have time for that tomorrow, 'll try to do it this Sunday.

**Comment by janekptacijarabaci** [comment]
See https://forum.palemoon.org/viewtopic.php?f=46&t=11661&p=82274#p82274

**Comment by wolfbeast** [comment]
@janekptacijarabaci I think it will be a lot more useful if you actually post relevant data in this very GitHub issue instead of linking back to our forum, to keep everything in one place that is relevant.

**Comment by wolfbeast** [comment]
Looks like your extension relies on global presence of promises, which isn't the case for us.
Extensions can draw on an internal promises implementation, though (promise.jsm).

**Comment by krisbr** [comment]
Okay, thanks for your reply. Since I'm not the original developer of this add-on I haven't worked with theses promises yet. But I'll look into them as soon as I've got some free time.

**Comment by beerisgood** [comment]
Your addon (version 1.2.2) works with Pale Moon 27.0.0 alpha1 !

**Comment by wolfbeast** [comment]
> Your addon (version 1.2.2) works with Pale Moon 27.0.0 alpha1 !

It should, since v27 has promises globally available :cake:

**Comment by krisbr** [comment]
I am pleased to hear that PassSec+ works well with the next Pale Moon version.
